import { DateIdea, Restaurant, DatePlan } from '../types';

export const MOCK_DATE_IDEAS: DateIdea[] = [
  {
    id: '1',
    title: 'Sunset Picnic at the Park',
    description: 'Pack a basket with artisan cheeses, fresh fruits, and a bottle of wine. Watch the golden hour together as the city lights up. Bring a cozy blanket and your favorite playlist.',
    category: 'romantic',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    rating: 4.9,
    reviewCount: 2847,
    priceRange: '$',
    estimatedDuration: '2-3 hours',
    location: 'Central Park',
    distance: '0.8 mi',
    tags: ['outdoor', 'romantic', 'budget-friendly', 'sunset'],
    isFeatured: true,
    isSaved: false,
    bestFor: ['First dates', 'Anniversaries', 'Spontaneous evenings'],
    tips: [
      'Arrive 45 min before sunset for the best spot',
      'Bring a bluetooth speaker',
      'Check weather forecast beforehand',
    ],
  },
  {
    id: '2',
    title: 'Cooking Class for Two',
    description: 'Learn to craft authentic Italian pasta from scratch with a professional chef. Enjoy wine pairings, take home recipes, and the satisfaction of eating what you created together.',
    category: 'foodie',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    rating: 4.8,
    reviewCount: 1203,
    priceRange: '$$$',
    estimatedDuration: '3 hours',
    location: 'The Kitchen Studio',
    distance: '1.2 mi',
    tags: ['indoor', 'foodie', 'interactive', 'memorable'],
    isFeatured: true,
    isSaved: false,
    bestFor: ['Date nights', 'Anniversaries', 'Couples looking for something new'],
    tips: [
      'Book at least a week in advance',
      'Mention dietary restrictions when booking',
      'Wear comfortable clothes you don\'t mind getting messy',
    ],
  },
  {
    id: '3',
    title: 'Rooftop Bar Hopping',
    description: 'Experience the city from above as you hop between the best rooftop bars downtown. Each stop offers unique cocktails, stunning views, and a different vibe for the evening.',
    category: 'nightlife',
    imageUrl: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=800',
    rating: 4.7,
    reviewCount: 985,
    priceRange: '$$',
    estimatedDuration: '4-5 hours',
    location: 'Downtown District',
    distance: '2.1 mi',
    tags: ['nightlife', 'city-views', 'social', 'drinks'],
    isFeatured: false,
    isSaved: false,
    bestFor: ['Night owls', 'City explorers', 'Special occasions'],
    tips: [
      'Start early to avoid long waits',
      'Make reservations at the most popular spots',
      'Dress to impress — most have a smart-casual dress code',
    ],
  },
  {
    id: '4',
    title: 'Art Museum & Gallery Walk',
    description: 'Explore local art galleries and the city museum together. Discuss what moves you, discover each other\'s tastes, and end with coffee at the museum café.',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=800',
    rating: 4.6,
    reviewCount: 743,
    priceRange: '$$',
    estimatedDuration: '3-4 hours',
    location: 'Arts District',
    distance: '1.5 mi',
    tags: ['cultural', 'indoor', 'intellectual', 'conversation'],
    isFeatured: false,
    isSaved: false,
    bestFor: ['Art lovers', 'First dates', 'Rainy days'],
    tips: [
      'Check for special exhibitions in advance',
      'Many museums are free on certain days',
      'The café closes an hour before the museum',
    ],
  },
  {
    id: '5',
    title: 'Kayaking at Sunrise',
    description: 'Rent kayaks and paddle out to watch the sunrise together on the lake. Pack thermoses of coffee and pastries. The calm morning water makes for a magical, peaceful experience.',
    category: 'adventure',
    imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    rating: 4.9,
    reviewCount: 567,
    priceRange: '$$',
    estimatedDuration: '2-3 hours',
    location: 'Lake Vista',
    distance: '8.5 mi',
    tags: ['outdoor', 'adventure', 'active', 'sunrise', 'nature'],
    isFeatured: true,
    isSaved: false,
    bestFor: ['Adventure couples', 'Active dates', 'Nature lovers'],
    tips: [
      'Sunrise varies — check the time and plan accordingly',
      'Wear layers, it\'s cold on the water in the morning',
      'No experience needed, but life jackets are a must',
    ],
  },
  {
    id: '6',
    title: 'Netflix Night Done Right',
    description: 'Transform your living room into a luxury cinema. Build a cozy fort with fairy lights, order your favorite takeout, and have a curated movie marathon with handpicked films.',
    category: 'cozy',
    imageUrl: 'https://images.unsplash.com/photo-1585844384734-d5fe5d6bb958?w=800',
    rating: 4.5,
    reviewCount: 3421,
    priceRange: '$',
    estimatedDuration: 'All evening',
    tags: ['indoor', 'cozy', 'budget-friendly', 'relaxed'],
    isFeatured: false,
    isSaved: false,
    bestFor: ['Tired couples', 'Rainy nights', 'Stay-at-home dates'],
    tips: [
      'Set the mood with fairy lights and candles',
      'Prepare movie snacks — make it a whole experience',
      'Let each person pick one movie for a double feature',
    ],
  },
  {
    id: '7',
    title: 'Couples Spa Day',
    description: 'Indulge in a full day of pampering together. Side-by-side massages, facials, and access to hot tubs and saunas. Leave feeling refreshed and deeply connected.',
    category: 'romantic',
    imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800',
    rating: 4.8,
    reviewCount: 892,
    priceRange: '$$$$',
    estimatedDuration: '4-6 hours',
    location: 'Serenity Spa & Wellness',
    distance: '3.2 mi',
    tags: ['romantic', 'luxury', 'relaxing', 'pampering'],
    isFeatured: true,
    isSaved: false,
    bestFor: ['Anniversaries', 'Valentine\'s Day', 'Special milestones'],
    tips: [
      'Book the couples suite for a private experience',
      'Arrive 30 minutes early to enjoy the amenities',
      'Don\'t eat a heavy meal beforehand',
    ],
  },
  {
    id: '8',
    title: 'Live Jazz & Dinner Night',
    description: 'Dress up and head to an intimate jazz club for a live performance. Enjoy craft cocktails and a gourmet dinner while the music sets the perfect romantic atmosphere.',
    category: 'nightlife',
    imageUrl: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
    rating: 4.7,
    reviewCount: 1156,
    priceRange: '$$$',
    estimatedDuration: '3-4 hours',
    location: 'Blue Note Lounge',
    distance: '2.8 mi',
    tags: ['nightlife', 'romantic', 'music', 'dinner', 'dressy'],
    isFeatured: false,
    isSaved: false,
    bestFor: ['Special occasions', 'Music lovers', 'Romantic evenings'],
    tips: [
      'Reserve a table near the stage for the best experience',
      'The late-night sets (9 PM+) are usually the most energetic',
      'Smart casual to formal attire recommended',
    ],
  },
];

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'r1',
    name: 'Rosé & Dine',
    cuisine: 'French-Mediterranean',
    description: 'An intimate bistro with candlelit tables, French-inspired cuisine, and an extensive wine list. The perfect backdrop for a romantic evening.',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    images: [
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
      'https://images.unsplash.com/photo-1428515329893-6e8ee6f2b69d?w=800',
    ],
    rating: 4.8,
    reviewCount: 1247,
    priceRange: '$$$',
    address: '127 Elm Street, Downtown',
    distance: '0.9 mi',
    phone: '+1 (555) 234-5678',
    ambiance: ['Intimate', 'Romantic', 'Candlelit', 'Quiet'],
    features: ['Valet Parking', 'Private Dining', 'Wine Cellar', 'Outdoor Terrace'],
    isOpen: true,
    isVerified: true,
    hours: [
      { day: 'Mon-Thu', open: '5:00 PM', close: '10:00 PM' },
      { day: 'Fri-Sat', open: '5:00 PM', close: '11:30 PM' },
      { day: 'Sunday', open: '4:00 PM', close: '9:00 PM' },
    ],
    availableSlots: [
      { time: '6:00 PM', available: 2, total: 4 },
      { time: '7:00 PM', available: 1, total: 4 },
      { time: '7:30 PM', available: 3, total: 4 },
      { time: '8:00 PM', available: 0, total: 4 },
      { time: '8:30 PM', available: 2, total: 4 },
      { time: '9:00 PM', available: 4, total: 4 },
    ],
  },
  {
    id: 'r2',
    name: 'Ember & Oak',
    cuisine: 'American Steakhouse',
    description: 'Premium aged steaks, craft cocktails, and a sophisticated atmosphere. Ember & Oak is where celebrations happen.',
    imageUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800',
    images: [
      'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800',
    ],
    rating: 4.7,
    reviewCount: 2103,
    priceRange: '$$$$',
    address: '45 Harbor Blvd, Waterfront',
    distance: '1.4 mi',
    phone: '+1 (555) 345-6789',
    ambiance: ['Upscale', 'Modern', 'Sophisticated', 'Lively'],
    features: ['Full Bar', 'Private Events', 'Chef\'s Table', 'Waterfront View'],
    isOpen: true,
    isVerified: true,
    hours: [
      { day: 'Mon-Thu', open: '5:30 PM', close: '10:00 PM' },
      { day: 'Fri-Sat', open: '5:00 PM', close: '11:00 PM' },
      { day: 'Sunday', open: 'Closed', close: '' },
    ],
    availableSlots: [
      { time: '5:30 PM', available: 4, total: 6 },
      { time: '6:00 PM', available: 2, total: 6 },
      { time: '6:30 PM', available: 0, total: 6 },
      { time: '7:00 PM', available: 1, total: 6 },
      { time: '8:00 PM', available: 3, total: 6 },
      { time: '9:00 PM', available: 5, total: 6 },
    ],
  },
  {
    id: 'r3',
    name: 'Sakura Garden',
    cuisine: 'Japanese Kaiseki',
    description: 'Authentic Japanese kaiseki dining with a seasonal omakase menu. Each dish is a work of art crafted from the freshest ingredients.',
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800',
    images: [
      'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800',
    ],
    rating: 4.9,
    reviewCount: 834,
    priceRange: '$$$$',
    address: '88 Garden Row, Midtown',
    distance: '2.1 mi',
    phone: '+1 (555) 456-7890',
    ambiance: ['Zen', 'Elegant', 'Quiet', 'Authentic'],
    features: ['Omakase Menu', 'Sake Pairing', 'Private Tatami Room', 'Chef Interaction'],
    isOpen: true,
    isVerified: true,
    hours: [
      { day: 'Tue-Thu', open: '6:00 PM', close: '9:30 PM' },
      { day: 'Fri-Sat', open: '5:30 PM', close: '10:30 PM' },
      { day: 'Sun-Mon', open: 'Closed', close: '' },
    ],
    availableSlots: [
      { time: '6:00 PM', available: 2, total: 3 },
      { time: '6:30 PM', available: 1, total: 3 },
      { time: '7:00 PM', available: 0, total: 3 },
      { time: '7:30 PM', available: 3, total: 3 },
      { time: '8:00 PM', available: 1, total: 3 },
    ],
  },
  {
    id: 'r4',
    name: 'The Garden Terrace',
    cuisine: 'Contemporary American',
    description: 'A stunning outdoor dining experience with a glass-covered terrace, lush greenery, and seasonal farm-to-table cuisine. Perfect for daytime or evening dining.',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    images: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    ],
    rating: 4.6,
    reviewCount: 1678,
    priceRange: '$$$',
    address: '220 Park Avenue, Uptown',
    distance: '0.6 mi',
    phone: '+1 (555) 567-8901',
    ambiance: ['Garden', 'Bright', 'Airy', 'Relaxed Upscale'],
    features: ['Outdoor Terrace', 'Brunch Menu', 'Craft Cocktails', 'Dog Friendly'],
    isOpen: true,
    isVerified: true,
    hours: [
      { day: 'Mon-Fri', open: '11:00 AM', close: '10:00 PM' },
      { day: 'Sat-Sun', open: '9:00 AM', close: '11:00 PM' },
    ],
    availableSlots: [
      { time: '7:00 PM', available: 5, total: 8 },
      { time: '7:30 PM', available: 3, total: 8 },
      { time: '8:00 PM', available: 2, total: 8 },
      { time: '8:30 PM', available: 6, total: 8 },
      { time: '9:00 PM', available: 4, total: 8 },
    ],
  },
];

export const MOCK_PLANS: DatePlan[] = [
  {
    id: 'p1',
    title: 'Anniversary Extravaganza',
    date: '2026-04-15',
    time: '5:00 PM',
    notes: 'Sarah\'s favorite flowers are sunflowers. Don\'t forget the reservations at Rosé & Dine!',
    items: [
      {
        id: 'pi1',
        type: 'activity',
        title: 'Couples Spa at Serenity',
        description: '90-minute couples massage',
        time: '2:00 PM',
        duration: '2 hours',
        cost: 280,
        location: 'Serenity Spa',
        isCompleted: false,
      },
      {
        id: 'pi2',
        type: 'restaurant',
        title: 'Dinner at Rosé & Dine',
        description: 'Reservation for 2 at 7:00 PM',
        time: '7:00 PM',
        duration: '2 hours',
        cost: 150,
        location: '127 Elm Street',
        isCompleted: false,
      },
      {
        id: 'pi3',
        type: 'activity',
        title: 'Rooftop Cocktails',
        description: 'End the night with drinks and city views',
        time: '9:30 PM',
        duration: '1.5 hours',
        cost: 60,
        isCompleted: false,
      },
    ],
    totalBudget: 490,
    status: 'upcoming',
    createdAt: '2026-03-01T10:00:00Z',
  },
];
